# Generated by Django 5.2.4 on 2025-11-19 16:29
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("maxMin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "idCliente",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("pais", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("ciudad", models.CharField(max_length=200)),
                (
                    "tipoCliente",
                    models.CharField(default="Cliente Nuevo", max_length=20),
                ),
                ("numTransacciones", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": '"administracion"."clientes"',
            },
        ),
        migrations.CreateModel(
            name="Caducidades",
            fields=[
                (
                    "idCaducidad",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("fechaCaducidad", models.DateField()),
                ("cantidad", models.IntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productoCaducidad",
                        to="maxMin.productos",
                    ),
                ),
            ],
            options={
                "db_table": '"produccionlogistica"."caducidades"',
            },
        ),
        migrations.CreateModel(
            name="Ventas",
            fields=[
                (
                    "idVenta",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("fecha", models.DateTimeField()),
                (
                    "tipoCliente",
                    models.CharField(default="Cliente Nuevo", max_length=20),
                ),
                ("paisVenta", models.CharField(max_length=100)),
                ("estadoVenta", models.CharField(max_length=100)),
                ("ciudadVenta", models.CharField(max_length=200)),
                ("unidad", models.CharField(max_length=20)),
                ("vendedor", models.CharField(max_length=200)),
                ("total", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasCliente",
                        to="reporteVentas.clientes",
                    ),
                ),
            ],
            options={
                "db_table": '"administracion"."ventas"',
            },
        ),
        migrations.CreateModel(
            name="VentasPVH",
            fields=[
                ("idPVH", models.BigAutoField(primary_key=True, serialize=False)),
                ("cantidad", models.BigIntegerField()),
                (
                    "precioUnitario",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "producto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasPVHProducto",
                        to="maxMin.productos",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventasPVHVenta",
                        to="reporteVentas.ventas",
                    ),
                ),
            ],
            options={
                "db_table": '"administracion"."ventaspvh"',
            },
        ),
    ]
