# Generated by Django 5.2.4 on 2025-10-30 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reporteVentas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caducidades",
            old_name="productoId",
            new_name="producto",
        ),
        migrations.RenameField(
            model_name="ventas",
            old_name="idCliente",
            new_name="cliente",
        ),
        migrations.RenameField(
            model_name="ventaspva",
            old_name="idProducto",
            new_name="producto",
        ),
        migrations.RenameField(
            model_name="ventaspvh",
            old_name="idVenta",
            new_name="venta",
        ),
    ]
