# Generated by Django 5.2.4 on 2025-11-19 16:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "idProductoTmp",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("idProducto", models.BigIntegerField(default=0)),
                ("nombre", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=100)),
                ("marca", models.CharField(default="", max_length=150)),
                ("maxActual", models.IntegerField(default=0)),
                ("minActual", models.IntegerField(default=0)),
                ("existenciaActual", models.IntegerField(default=0)),
                ("existenciaOC", models.IntegerField(default=0)),
                ("categoria", models.CharField(default="", max_length=150)),
                ("tipo", models.CharField(default="", max_length=100)),
                ("fechaCreacion", models.DateTimeField(default=datetime.datetime.now)),
                ("proveedor", models.CharField(default="", max_length=200)),
                ("tiempoEntrega", models.IntegerField(default=0)),
            ],
            options={
                "db_table": '"produccionlogistica"."productos"',
            },
        ),
        migrations.CreateModel(
            name="MaterialPI",
            fields=[
                (
                    "idMaterialPI",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("cantidad", models.FloatField()),
                (
                    "idHijo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="MaterialProducto",
                        to="maxMin.productos",
                    ),
                ),
                (
                    "idPadre",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="padreProducto",
                        to="maxMin.productos",
                    ),
                ),
            ],
            options={
                "db_table": '"produccionlogistica"."materialpi"',
            },
        ),
    ]
