# Generated by Django 5.2.4 on 2025-08-05 14:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=15)),
                ('marca', models.CharField(default='', max_length=150)),
                ('maxActual', models.IntegerField()),
                ('minActual', models.IntegerField()),
                ('existenciaActual', models.IntegerField(default=0)),
                ('categoria', models.CharField(default='', max_length=150)),
                ('proveedor', models.CharField(default='', max_length=200)),
                ('tiempoEntrega', models.IntegerField(default=0)),
            ],
            options={
                'db_table': '"produccionlogistica"."insumos"',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100)),
                ('marca', models.CharField(default='', max_length=150)),
                ('maxActual', models.IntegerField()),
                ('minActual', models.IntegerField()),
                ('existenciaActual', models.IntegerField(default=0)),
                ('categoria', models.CharField(default='', max_length=150)),
                ('tipoProducto', models.CharField(default='', max_length=100)),
                ('fechaCreacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': '"produccionlogistica"."productos"',
            },
        ),
        migrations.CreateModel(
            name='MaterialPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxMin.insumos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxMin.productos')),
            ],
            options={
                'db_table': '"produccionlogistica"."materialPI"',
                'unique_together': {('producto', 'insumo')},
            },
        ),
    ]
