# Generated by Django 5.2.4 on 2025-08-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxMin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materialpi',
            table='"produccionlogistica"."materialpi"',
        ),
    ]
